### ISSUE TITLE
教学视频在线地址、网盘地址。

### ISSUE THREAD

**Issue by zhangjinming** [xxlllq/system_architect#1]
Hello  教学视频链接不存在，请补上。谢谢。

**Comment by xxlllq** [comment]
您好，这是视频教程链接：
链接: https://pan.baidu.com/s/1siBSEEF9WxKkKXwdl4OncQ 提取码: 4w7v

**Comment by sailingsky** [comment]
非常感谢提供的资源

**Comment by xxlllq** [comment]
> 非常感谢提供的资源

客气了，共同进步。

**Comment by paul-chen** [comment]
非常感谢！

**Comment by xxlllq** [comment]
> 非常感谢！准备考架构师，很有用的资料！

不客气，非常高兴能提供帮助！

**Comment by ITGUIWSG** [comment]
大气

**Comment by mandy-one** [comment]
感谢大佬！

**Comment by xxlllq** [comment]
> 感谢大佬！

不客气的。

**Comment by xxlllq** [comment]
> 感谢大佬！



> 大气

欢迎入群。

**Comment by xxlllq** [comment]
不客气，欢迎加群。



------------------ 原始邮件 ------------------
发件人: "mandy-one"<notifications@github.com>; 
发送时间: 2019年7月1日(星期一) 上午10:20
收件人: "xxlllq/2018_system_architect"<2018_system_architect@noreply.github.com>; 
抄送: "xxl"<xxlllq@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [xxlllq/2018_system_architect] Hello  教学视频链接不存在，请补上。 (#1)




感谢大佬！

**Comment by JcookieChen** [comment]
谢谢大佬

**Comment by colerape** [comment]
谢谢分享。

**Comment by xxlllq** [comment]
不客气，欢迎加群。




------------------ 原始邮件 ------------------
发件人: "寒"<notifications@github.com>;
发送时间: 2019年7月5日(星期五) 中午11:29
收件人: "xxlllq/2018_system_architect"<2018_system_architect@noreply.github.com>;
抄送: "xxl"<xxlllq@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [xxlllq/2018_system_architect] Hello  教学视频链接不存在，请补上。 (#1)




谢谢分享。

**Comment by tangston** [comment]
非常谢谢，视频我都下下来了，考试努力，对大三生只能知识入门

**Comment by lbj031** [comment]
谢谢分享。

**Comment by liker5092** [comment]
very good!!!tku very much!!

**Comment by fei8326** [comment]
感谢感谢，准备今年考下。

**Comment by qiufushuang** [comment]
非常感谢

**Comment by dusaisai** [comment]
thanks,it is very useful

**Comment by GoKingStones** [comment]
非常感谢

**Comment by qylixin** [comment]
非常感谢！

**Comment by longProgrammer** [comment]
感谢分享

**Comment by spring1234** [comment]
感谢分享，内容很强大。

**Comment by qilongyin** [comment]
太赞了 这也太强了

**Comment by xingchaoma** [comment]
十分感谢无私分享~

**Comment by mengshu** [comment]
非常感谢

**Comment by StearArre** [comment]
> 努力，对大三生只能知识

你好，可以分享一下资料的网盘地址么

**Comment by humbinal** [comment]
https://www.bilibili.com/video/BV1KE411M7Cg

**Comment by no2aurora** [comment]
thank you very much

**Comment by zhcngs** [comment]
Thank you, useful! 谢谢这世界上最大同性交友社区的馈赠，谢谢楼主的分享！不做伸手党，谢谢！

**Comment by anJava** [comment]
非常感谢

**Comment by liujq2526859** [comment]
非常感谢

**Comment by nikylin** [comment]
非常谢谢楼主，今年打算备考

**Comment by i402097836** [comment]
> B站有网友分享的视频链接：

1、2020年：https://www.bilibili.com/video/BV1Zf4y157zY 。  该链接已不能访问

**Comment by xxlllq** [comment]
> > B站有网友分享的视频链接：
> 
> 1、2020年：https://www.bilibili.com/video/BV1Zf4y157zY 。 该链接已不能访问

应该是提供链接的网友删除了，后续有相关链接再更新。

**Comment by MemoryExplosion** [comment]
视频链接失效了

**Comment by kent666a** [comment]
非常感谢

**Comment by wangymd** [comment]
B站的学习视频有云盘地址吗？ 线上下架了！
