### ISSUE TITLE
2020年真题案例分析五的问题2答案是错误的吧

### ISSUE THREAD

**Issue by zhangyenull** [xxlllq/system_architect#11]
路径：system_architect/真题(截至2020年)【推荐】/历年真题及解析合并版本（截至2020年）/2020年/2020年系统架构师考试科目二：案例分析真题+解析.pdf
我的答案
(7)f.   JSP
(6)c.  view layer
(5)d.  controller layer
(4)i.   Spring
(3)h.  myBatis
(2)e.  persistence Layer
(1)a. connection pool

**Comment by xxlllq** [comment]
> 路径：system_architect/真题(截至2020年)【推荐】/历年真题及解析合并版本（截至2020年）/2020年/2020年系统架构师考试科目二：案例分析真题+解析.pdf
> 我的答案
> (7)f. JSP
> (6)c. view layer
> (5)d. controller layer
> (4)i. Spring
> (3)h. myBatis
> (2)e. persistence Layer
> (1)a. connection pool

感谢提醒，已修正答案。
