### ISSUE TITLE
推荐个软考链接吧！

### ISSUE THREAD

**Issue by i0Ek3** [xxlllq/system_architect#14]
顺便推荐个链接吧，跨步软考，www.kuabu.xyz, 里面的资料也挺全，就是下载链接是百度云的。
另外，软考其实挺重要的，无论在企业还是体制上班，还有些国家也是认可的。
最后，多谢作者分享。

**Comment by xxlllq** [comment]
> 顺便推荐个链接吧，跨步软考，www.kuabu.xyz, 里面的资料也挺全，就是下载链接是百度云的。
> 另外，软考其实挺重要的，无论在企业还是体制上班，还有些国家也是认可的。
> 最后，多谢作者分享。

跨步软考，一般吧，好多资料都是比较陈旧的了，都没怎么更新过。
