### ISSUE TITLE
教材百度资源不在

### ISSUE THREAD

**Issue by panthoen** [xxlllq/system_architect#4]
大佬可以把教材的资源补上么，谢谢了啦

**Comment by xxlllq** [comment]
最近百度网盘有些资源分享总是【审核失败】，你可以选择通过QQ群文件的下载方式获取！

**Comment by xxlllq** [comment]
> 大佬可以把教材的资源补上么，谢谢了啦

最近百度网盘有些资源分享总是【审核失败】，你可以选择通过QQ群文件的下载方式获取！

**Comment by panthoen** [comment]
好的，谢谢大佬

**Comment by nigelye** [comment]
感谢大佬~~~

**Comment by okaki666** [comment]
大佬，《系统架构设计师考试32小时通关》的资源没有找到了，链接1已经失效了

**Comment by xxlllq** [comment]
> 大佬，《系统架构设计师考试32小时通关》的资源没有找到了，链接1已经失效了

加QQ群，去群文件下载吧，我的百度网盘链接分享就立即失效了。

**Comment by xxlllq** [comment]
> 大佬，《系统架构设计师考试32小时通关》的资源没有找到了，链接1已经失效了

因为百度云盘链接经常失效，故提供了一份阿里云盘链接。请查看https://github.com/xxlllq/system_architect/issues/4#issuecomment-545692908

**Comment by digitalmavica** [comment]
aliyun快多了, 谢谢XD

**Comment by hy0619** [comment]
阿里网盘打不开呀， 让我加群？？

**Comment by xxlllq** [comment]
> 阿里网盘打不开呀， 让我加群？？

可以打开的呢，如果实在不行就加群吧。
