### ISSUE TITLE
资源失效烦请更新

### ISSUE THREAD

**Issue by MyTestGit12138** [xxlllq/system_architect#7]
首先感谢作者提供了这么多复习资料，其中的视频、教材的云盘资料已失效，不知能否辛苦作者更新下链接，万分感谢

**Comment by xxlllq** [comment]
**您好，这是网友提供的视频教程链接：
链接: https://pan.baidu.com/s/1ov81e2qRsTC7mfTAS9YTGw 提取码: 22pp**
