### ISSUE TITLE
讲义文件

### ISSUE THREAD

**Issue by StearArre** [xxlllq/system_architect#8]
你好，大佬
csdn积分不足，可否提供下讲义的网盘下载方式。跪求~
系统架构师考试培训讲义-2019 来源于CSDN：https://download.csdn.net/download/b410739945/12351264

**Comment by xxlllq** [comment]
你通过邮箱或者QQ联系我一下，我帮你下载。

**Comment by xxlllq** [comment]
> 你好，大佬
> csdn积分不足，可否提供下讲义的网盘下载方式。跪求~
> 系统架构师考试培训讲义-2019（来源于CSDN：[https://download.csdn.net/download/b410739945/12351264）](https://download.csdn.net/download/b410739945/12351264%EF%BC%89)

去某宝找CSDN代下载，1-2RMB就行了。

**Comment by StearArre** [comment]
> > 你好，大佬
> > csdn积分不足，可否提供下讲义的网盘下载方式。跪求~
> > 系统架构师考试培训讲义-2019 来源于CSDN：[https://download.csdn.net/download/b410739945/12351264）](https://download.csdn.net/download/b410739945/12351264%EF%BC%89
> 
> 去某宝找CSDN代下载，1-2RMB就行了。

好的，感谢~
