### ISSUE TITLE
教材的链接已失效

### ISSUE THREAD

**Issue by lcyzgdy** [xxlllq/system_architect#9]
感谢作者的分享的资料，教材的网盘链接已经失效，烦请更新？

**Comment by xxlllq** [comment]
> 感谢作者的分享的资料，教材的网盘链接已经失效，烦请更新？

链接：https://pan.baidu.com/s/1O3KOd12ylECBzzRvoY7K5g 
提取码：6666 
复制这段内容后打开百度网盘手机App，操作更方便哦

如果通过网盘链接无法下载，您可以选择通过[QQ群文件](https://github.com/xxlllq/system_architect/issues/3)的下载方式获取！
